### ISSUE TITLE
Date not formatting properly in /books table

### ISSUE THREAD

**Issue by madaley1** [Panethnic-Pourovers/admin#17]
![image](https://github.com/Panethnic-Pourovers/admin/assets/61160473/77d8bab9-89d1-44ca-b381-878d539c99d2)
Per the image, dates aren't formatting right now. 

I'm adding this as an issue as it may not actually require changing, rather it may require some data processing to get rid of invalid date ranges, but as this is going to require more diagnostics as we continue developing I felt it was better to add here than a solo ticket.

**Comment by madaley1** [comment]
Also it should be noted that as the example book has never been checked out, I'm not sure if this is an issue of lastCheckedOut being undefined, or if it is actually an issue of formatting.

**Comment by egoroza** [comment]
I'll take a look! Have you tried logging the values in the console? If it's simply a format issue we should be able to fix that easily. If the book has never been checked out and has a value for `lastCheckedOut` we'll want to add a conditional case for that when displaying the data

Couple things we could do here if that is the case. Quick fix is just to add a formatting function on the FE. I forget what PR I mentioned this in; but it might be a good idea to create a server endpoint to fetch the data and handle that logic there. Essentially we would create a new folder at the root `/server` and add our endpoints there. Either way, both of these solutions would be fine, it's just a matter of whether we want to perform this on the FE vs. BE and performance-wise (at least right now) we don't have a significant amount of data so it won't really make a difference

**Comment by madaley1** [comment]
I haven't looked too far into this yet! I'm assuming we'll end up with the conditional case either way though. I just saw it and wanted to make note for future reference, since I haven't worked with storing date objects directly in a db before!

**Comment by MichaelShingo** [comment]
Fixed formatting by converting Date object to string.
